# Generated by Django 4.0.2 on 2022-05-20 17:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='make_announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret', models.DateField(verbose_name='retrieval')),
                ('subm', models.DateField(verbose_name='submission')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contacts', models.CharField(max_length=11, unique=True, verbose_name='contacts')),
                ('parents', models.CharField(max_length=100, verbose_name='parents')),
                ('adviser', models.CharField(choices=[('Pambid', 'Ms. Gina Pambid'), ('Pendo', 'Mrs. Aurea Pendo'), ('Loresca', 'Ms. Adelia Loresca'), ('Bocar', 'Mrs. Maria Lina Bocar'), ('Camcho', 'Ms. Ella Mae Camcho'), ('Neypes', 'Mr. Khristine Neypes'), ('Niemes', 'Renee Rose Niemes'), ('Apostol', 'Mrs. Teresita Apostol')], max_length=50, verbose_name='adviser')),
                ('gradelvl', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=11, verbose_name='gradelvl')),
                ('section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E'), ('F', 'Section F'), ('G', 'Section G')], max_length=50, verbose_name='section')),
                ('lrn', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('userType', models.CharField(choices=[('Adviser', 'Adviser'), ('Student', 'Student'), ('Admin', 'Admin')], max_length=50, verbose_name='userType')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('lrn_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='student_id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('quarter', models.CharField(max_length=20, verbose_name='quarter')),
                ('week', models.CharField(max_length=20, verbose_name='week')),
                ('modules', models.CharField(max_length=20, verbose_name='modules')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='scholarship',
            fields=[
                ('lrn_scholarship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MESSYSTEMapp.studentinfo', verbose_name='scholarship_id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('amount', models.CharField(choices=[('1000', '1000'), ('2000', '2000'), ('3000', '3000')], max_length=50, verbose_name='amount')),
            ],
        ),
    ]
