# Generated by Django 4.0.2 on 2022-05-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MESSYSTEMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='lrn_scholarship',
            new_name='lrn_student',
        ),
    ]
