# Generated by Django 4.0.2 on 2022-05-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MESSYSTEMapp', '0002_rename_lrn_scholarship_scholarship_lrn_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='lrn_student',
            new_name='lrn_scholarship',
        ),
    ]
